### PR TITLE
Added @tunnel to p:option (description only)

### PR DESCRIPTION
**Pull request by eriksiegel**
Hi. I added some text about the tunneling option to the specification. I don't feel enough at home to make the (probably simple) change to the schema also, so that remains to be done. 
It might also be that my writings are not exact enough for the implementors but it can serve as a starting point?

### CODE REVIEW

**Comment by eriksiegel** [comment]
We could make it easy on ourselves (like Tom Jones sings, I can hear him in my head while I write this) and make the rules as strict as we like.

Proposal:
- Tunneling implies required="false". Setting required="true" and tunnel="true"is an error
- You can set a tunnel option by either using an explicit with-option (this takes precedence) *or*, when there is no with-option for this option, having an option  in the calling stylesheet with the same name and tunnel="true"
- If you add a select attribute on option, this simply takes over when the option is not set, like always.

**Comment by xml-project** [comment]
I think this is a good approach, I agree with all three proposals.
Speaking of "easy solutions" (btw. I do not know the song): I doubt whether we need XS0088. If we leave it open, the appearing value, where ever it come from (explicit, tunnelling, default) has to match the type for the option in question, otherwise it's XD0036.
Doing it this way would also allow to cast types which would be prohibited by comparing string because an xs:integer value is castable to xs:decimal, but "xs:integer" is not equal to "xs:decimal".

**Comment by eriksiegel** [comment]
All right, I think the PR was a bit too premature. I reject it. The text needs to be changed anyway *after* we reach full consensus.

**Comment by xml-project** [comment]
@eriksiegel Do you think it would be useful to copy your proposals to the related issue?

**Comment by eriksiegel** [comment]
Yes, I will do this today.

**Pull request closed without merging**
