### PR TITLE
Build changes for portability

### PR DESCRIPTION
**Pull request by ndw**
I believe these changes fix the build problems on Windows.

### CODE REVIEW

**Comment by eriksiegel** [comment]
Thanks! Very busy now, will try to look into this tomorrow.

**Comment by xml-project** [comment]
I see: How to test it?

**Comment by ndw** [comment]
Apply the PR, then run `gradle --no-daemon clean allspecs`. It should run 140 tasks and populate `build/dist` with all the specs.

**Comment by xml-project** [comment]
I never build my local system but always use Travis on my repo. So any change should not affect me. Right?

**Comment by eriksiegel** [comment]
Right. How can I get the changes from this pull request on my machine so I can test them? I'm looking in the help but this isn't mentioned or I overlook it. Anybody with enough GIT knowledge knows?

**Comment by eriksiegel** [comment]
Never mind, i think I found the right help page, finally

**Comment by ndw** [comment]
This works for me, it works for Travis, and I think it's an improvement. Worst case, Erik, it still won't work for you, but if that's the case, let me know.
I'm going to merge it to unblock some other work I'm doing.

**Comment by eriksiegel** [comment]
@ndw It works now on my machine but the command you specified, gradle --no-daemon clean allspecs, took 4:30 minutes! Is that normal?

**Comment by ndw** [comment]
Apparently :disappointed: 
On my Linux box it takes about 30 seconds, but when I ran it on my Windows VM, it took just over four minutes. I assumed that was because my VM has insufficient memory or something, but I guess it's just a Windows issue.
We can set you up with Travis so the builds will happen automatically when you commit to your local repo.

**Pull request merged**
