### PR TITLE
Attempt to fix 380

### PR DESCRIPTION
**Pull request by xml-project**
Fixing issue #380 by explicitly saying, which results of `@select` are allowed.

### CODE REVIEW

**Comment by xml-project** [comment]
@ndw @gimsieke @eriksiegel 
Is there a problem with this PR? I thought it would be pretty uncontroversal.

**Comment by gimsieke** [comment]
The purpose is to exclude attribute and namespace nodes?

**Comment by xml-project** [comment]
Yes, because the specs say that a new document is created by wrapping a document-node around the select result if it is not a document-node.
Then it must be an error if "@select" returns atomic values, maps, arrays, function items, attributes or namespace nodes, right?

**Comment by gimsieke** [comment]
Atomic values, maps, arrays, and function items have already been excluded by reference to “nodes”. But yes, let’s go with explicitly listing the permitted types.
I originally thought we could refer to the selectable nodes using [`node()`](https://www.w3.org/TR/xslt-30/#d7e19631) in the XSLT pattern sense. But this includes only text, element, PI, and comment, not document nodes.

**Pull request merged**
