### PR TITLE
Text changes for issue #388

### PR DESCRIPTION
**Pull request by eriksiegel**
I tried to describe map attributes and moved the section about option attributes to the right location

### CODE REVIEW

**Comment by eriksiegel** [comment]
I now made "map-attribute" an official termdef. Better?

**Comment by eriksiegel** [comment]
Ok, datatype is now sequence type.
Also changed the wording a bit because I saw the definition of AVT was different then I thought it was.

**Comment by gimsieke** [comment]
[Men Without Hats](https://en.wikipedia.org/wiki/The_Safety_Dance), apparently…

**Comment by eriksiegel** [comment]
Aren't we all (in the committee). I haven't seen a hat on our heads in Leipzig :-)

**Pull request merged**
