### PR TITLE
Removed globbing on p:load, added rudimentary p:load-directory-list. …

### PR DESCRIPTION
**Pull request by eriksiegel**
…See #433 and #325

### CODE REVIEW

**Comment by xml-project** [comment]
... and I would suggest to have the regex with as="xs:string+", so I can write more then one regex. Semantics: Something is included, if it matches one of the include-filters and NONE of the exclude-filters.

**Comment by eriksiegel** [comment]
@xml-project This is how I remember it. We removed globbing fro p:document and p:load and decided on a special step p:load-directory list that would support globbing. That's also my interpretation of the consensus on #325.

And anyway, the description of p:load-directory-list is almost a verbatim copy of p:directory-list. So your comments on include/exclude filters etc. apply also on p:directory-list.

**Comment by xml-project** [comment]
@eriksiegel I will never ever question your memory. I am just not sure what "Do away with globbing" in the minutes means.

Concerning p:directory-list and include/exclude-filter: You are certainly right, and I remember me having made this suggestion, but I should record it as an issue.

**Comment by xml-project** [comment]
I just read Norm's addition to the minutes and I still do not have a clue, what "Do away with globbing" means.
Proposal: Lets merge the pull request and talk about it in next telcon.

**Comment by eriksiegel** [comment]
@xml-project Good suggestion. Unless anybody objects, I will merge the pull-request somewhere tomorrow

**Comment by gimsieke** [comment]
Re https://github.com/xproc/3.0-specification/pull/434#issuecomment-402022338: I think “do away with globbing” was only aimed at `p:load` and `p:document`. Another possible explanation is that it says “use regexes instead of glob patterns”. It can well be that i wrote this sentence first, when there was consensus not to glob `p:load` and `p:document`, and then I didn’t update it in the light of the more nuanced discussion that ensued.

**Pull request merged**
