### PR TITLE
Timeout on http request issue #78

### PR DESCRIPTION
**Pull request by xml-project**
Proposal for attributes timeout and fail-on-timeout in c:request of p:http-request

### CODE REVIEW

**Comment by ndw** [comment]
I hate to be argumentative, but why is this on the `p:http-request` step and not part of the `c:request`? It feels to me like it should be part of the request.

**Comment by gimsieke** [comment]
But the timeout, as Achim proposed it, is on `c:request`, not on `p:http-request`. 
I was thinking that we can do without a timeout on the request but instead use the generic timeout mechanism. Processors should be allowed to selectively support the generic timeout only on specific, implementation-defined, steps. This would allow them to support a timeout only on `p:http-request`, for example.
As I suggested in the other comment, maybe we should discuss the whole timeout issue (HTTP request and otherwise) in a hangout.

**Comment by ndw** [comment]
A request timeout is a pretty common feature of http libraries. There are good reasons for sometimes wanting to change it (for example, making it very short if you're just pinging to see if a service is available). Sorry I misunderstood where this was being proposed, Achim.

**Comment by xml-project** [comment]
I have added the note on p:http-request as requested by @gimsieke 
Can I merge this now?

**Pull request merged**
