### PR TITLE
How do steps effect document properties?

### PR DESCRIPTION
**Pull request by ndw**
This PR attempts to resolve issue #85 

Even if it's imperfect, it's a start.

### CODE REVIEW

**Comment by ndw** [comment]
I thought set properties would set the properties to precisely what you provided. So if you don't provide foo, it goes away.

I suppose we could add an "merge" attribute to say that the set properties should be added to the current properties.

**Comment by ndw** [comment]
I added a merge option to p:set-properties and updated the description.

I updated the description of p:split-sequence to preserve the properties.

I don't think, in general, that preserving the properties on XSLT is a good idea. The XSLT step is much too likely, IMHO, to change the document in ways that make them invalid. We'll can have p:with-document (the dual of p:with-properties) for the cases where you know you want to preserve them.

**Comment by gimsieke** [comment]
Do we have another place in the spec where we state to which extent the `base-uri` document property and what is returned by `fn:base-uri(/)` are kept in sync by the processor?
If there is some syncing, then we can add a note that points to this piece of prose, like “The `base-uri` property might be restored on the output because of `p:xslt`’s default behavior and because of the syncing between the `base-uri` property and an XML document’s base URI.”.

**Comment by ndw** [comment]
More good points, thank you! I made another pass through, assuring that we do specify that content-type and base-uri are always set, and consistent. I also took out the proxy documents section (issue #154) because I was in the neighborhood.

**Comment by ndw** [comment]
Foolishly, perhaps, I resolved a merge conflict in the GitHub UI. If it didn't work, things may be unrecoverable. As it is, it's probably beyond my skill to continue making edits to this PR.

**Comment by gimsieke** [comment]
Then perhaps try to merge it right now? Should further changes be necessary, we can file new issues.

**Comment by ndw** [comment]
Ok. I'm going to call that approval and give it a try :-)

**Pull request merged**
