### PR TITLE
Attempt to fix #125

### LINKED ISSUE #125: Error code for defect p:try
We currently have no error code for a p:try without a p:catch (or without a p:group).
Processors behave differently: XMLCalabash XS0027, MorganaXProc XS0044.
Both do not really fit. 

Proposal:
(a) Introduce a new static error XS1012, stating that a p:group and a p:catch is required for a p:try.
(b) Introduce a generic static error message XS1011 stating that it is a static error, if a non-step multi-container step has not the child steps required. This error could be used for p:try and also for an empty p:choose

### PR DESCRIPTION
**Pull request by xml-project**
Adding text for defective p:try and introducing XS1012.

### CODE REVIEW

**Comment by xml-project** [comment]
Are you thinking of
<p:try>
   <p:group>... </p:group>
   <p:finally> ... </p:finally>
</p:try>?
To make sense of this construct (apart from commenting out p:catches for debugging purposes) the finally block needs to be executed in any case: when p:group raises an error, finally needs to be executed before the error bubbles up. Is this your point? This would be a useful behaviour even if there are catch elements, because no element may catch the error raised.
Is it this, you have in mind?

**Comment by gimsieke** [comment]
I didn’t have anything in mind with respect to `p:finally`. I just noticed the [editorial note](http://spec.xproc.org/master/head/xproc30/#ednote-finally). I assume Norm put it there. 
Thinking about it now, I can imagine use cases both for `p:finally` in itself and also for a `p:finally` without a preceding `p:catch`. As you say, before the error bubbles up, `p:finally` can clean up temporary files and the like. So maybe we should stipulate that there be at least one `p:catch` or a `p:finally`. It might need further discussion.

**Comment by xml-project** [comment]
Added text to the editor's note on p:finally as requested by @gimsieke 
Merge?

**Comment by gimsieke** [comment]
Yes. I wonder to which (or rather, whose) repo the changes will go if I push the green button “Merge pull request“. If you feel comfortable merging it yourself, please go ahead.

**Comment by xml-project** [comment]
On the top of this page it says: 	xml-project  wants to merge 3 commits into xproc:master
This looks right to me, is it not?

**Comment by gimsieke** [comment]
Yes, it does. Should I push the button? (I’m just a bit cautious because last time around, the changes were merged into Norm’s repo and we never found out why.)

**Comment by xml-project** [comment]
Do it! Last time I merged, it went to the correct repo. So we could test your settings this time.

**Pull request merged**
