### PR TITLE
Revert PR 890

### PR DESCRIPTION
**Pull request by xml-project**
Attempt to solve #892 and https://github.com/xproc/3.0-steps/issues/251
by reverting pr #890 

As the discussion has shown, this PR was premature.

### CODE REVIEW

**Comment by xml-project** [comment]
I think we already have a way to change the base URI property of a document node:
```
<p:identity>
  <p:with-input>
    <p:inline xml:base="http://new-uri">{.}</p:inline>
  </p:with-input>
</p:identity>
```
If you look at all the problems and additional requirement that are to be fulfilled as a result of PR #890 I think it is simple not worth it.

**Comment by gimsieke** [comment]
In #892 you say:

> Now since we allow pipeline authors to overwrite proper base URI with arbitrary string in the document-properties map, an author might attempt to remove document's base URI or overwrite the proper value with a value which is not a proper URI.

Can’t the `p:inline` solution that you propose above be used by pipeline authors to assign “improper” base URIs to documents? If you want to prevent authors from doing so, you need to say that a base URI may never be changed, or only changed to what is a “valid” URI. 
In any case, I don’t see why, on the one hand, you want to allow the `p:inline` solution (or my clumsy `p:xslt` solution that already works with 1.0), in which authors can shoot themselves in their feet ad libitum, while on the other hand you want to rule out manipulation of a document node’s base URI by changing the `base-uri` document property.

**Comment by xml-project** [comment]
> Can’t the p:inline solution that you propose above be used by pipeline authors to assign “improper” base URIs to documents?

No, because it is an error according to the definition of "[xml:base](https://www.w3.org/TR/xmlbase/)" : "The terms base URI and relative URI are used in this specification as they are defined in [RFC 3986]."

**Comment by gimsieke** [comment]
So your main issue is that `base-uri` is `xs:anyURI` that can virtually be any string, according to XML Schema 1.1 Part?

Can we agree and specify that, in principle, the same (stricter, that is, RFC 3986 or rather LEIRI) rules apply to the `base-uri` property that apply to `@xml:base` attributes? 

But, as [XDM 3.1](https://www.w3.org/TR/xpath-datamodel-31/#namespace-names) says about namespace names, “implementations **may** reject character strings that are not valid URIs or IRIs, but they are not _required_ to do so.” 

Or phrased differently: “Although the `base-uri` property is an XDM 3.1 / XSD 1.1 `xs:anyURI` value, implementations may, but are not required to, reject strings that are not valid URIs according to the `xml:base` specification. Likewise, they may accept strings for the `@xml:base` attribute that are castable to `xs:anyURI` but do not strictly comply with the `xml:base` specification. It is a dynamic error XD… if the `base-uri` property or the `xml:base` attribute has a value that may not be used as a base URI.”

In practice, for example Saxon accepts `@xml:base` values that do not conform to the strict spec. This may or may not be a problem, and an XProc implementation is free to apply additional checks and raise this error.

**Comment by xml-project** [comment]
> So your main issue is that base-uri is xs:anyURI that can virtually be any string, according to XML Schema 1.1 Part?

The short answer would be "no". The longer one: I did not mention xs:anyURI in the issues and there is also no reference to xs:anyURI in [xml:base] or [RFC 3986]. Therefor I do not understand how this comes into play here.

**Comment by gimsieke** [comment]
I only try to understand your point. On multiple occasions you said that I didn’t get the point. Can you try to explain again what is problematic about the PRs that you want to revert?

**Comment by xml-project** [comment]
@gimsieke I will try to send you a mail over the weekend, but I am not sure this will work out, because I am busy with other things. Or we wait, until Norm tries to implement the specs and discovers the problems. Or, you could simply trust me. ;-))

**Comment by gimsieke** [comment]
Or you can try to explain it to me in a phone call. 

Anyway, Cologne is only a fortnight away, and we can discuss it there. 

Most of the time when there is a lack of common understanding of some matter, discussing it face to face is more productive than discussing it in a conference call which in turn is more productive than discussing it on some forum on the Internet…

Be assured that the reason that I didn’t quite grasp your point yet it is my dumbness and not bad faith / passive-agressiveness ;)

**Comment by xml-project** [comment]
I guess it may be simply my lack of expressiveness in English.

**Comment by gimsieke** [comment]
Ok, it was good to discuss it on the phone, @xml-project. Will send the plan how we propose to tackle the base URI issue to the editors later today.

**Pull request merged**
